[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
common_domain = { path = "../../feature/common/common_domain", features = [
  "error",
] }
serde = { workspace = true, features = ["derive"] }
