name: 'Build and deploy - dev'

on:
  push:
    branches: 
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      cache_id: hello-lambda
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            ./target/
          key: ${{ env.cache_id }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUSTC_HASH }}

      - name: Add target
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Install cross
        run: cargo install cross

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: build-lambda --use-cross --target aarch64-unknown-linux-gnu

      - name: Create flutter layer
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: create-flutter-layer
